# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_titanic',
                'doc_host': 'https://tomasellis.github.io',
                'git_url': 'https://github.com/tomasellis/nbdev_titanic',
                'lib_path': 'nbdev_titanic'},
  'syms': {'nbdev_titanic.core': {'nbdev_titanic.core.foo': ('core.html#foo', 'nbdev_titanic/core.py')}}}
