# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_core.ipynb.

# %% auto 0
__all__ = ['foo', 'test']

# %% ../nbs/01_core.ipynb 3
def foo(): pass

foo()

# %% ../nbs/01_core.ipynb 4
def test():
    a = "dunno"
    return 2 + 2
